name: Mule App Deployment

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        type: choice
        options: [DEV, UAT, PROD]
      java:
        description: "Java Version"
        required: true
        type: choice
        options: ['8', '17']
      commit:
        description: "Commit Message"
        required: true
        type: string

  # Automatic trigger on push to main
  push:
    branches:
      - master

env:
  DEFAULT_ENVIRONMENT: DEV
  DEFAULT_JAVA_VERSION: '17'
  DEFAULT_COMMIT_MESSAGE: 'Automated deployment from main branch'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Java version
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java || env.DEFAULT_JAVA_VERSION }}
      - name: Run Tests
        env: 
          cI: ${{secret.ANYPOINT_CLIENT_ID}}
          cS: ${{secret.ANYPOINT_CLIENT_SECRET}}
        run: mvn clean test

  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Java version
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java || env.DEFAULT_JAVA_VERSION }}
      - name: Build Application
        env: 
          cI: ${{secret.ANYPOINT_CLIENT_ID}}
          cS: ${{secret.ANYPOINT_CLIENT_SECRET}}
        run: mvn clean package -DskipTests

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Java version
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java || env.DEFAULT_JAVA_VERSION }}
      - name: Deploy to CloudHub 2.0
        env: 
          cI: ${{secret.ANYPOINT_CLIENT_ID}}
          cS: ${{secret.ANYPOINT_CLIENT_SECRET}}
        run: |
          mvn deploy \
            -DskipTests \
            -Denvironment=${{ inputs.environment || env.DEFAULT_ENVIRONMENT }} \
            -DcommitMessage="${{ inputs.commit || env.DEFAULT_COMMIT_MESSAGE }}"
